In [7]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

import gym
import gym_anytrading
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import DummyVecEnv

In [8]:
df = pd.read_csv('SOL_1H.csv')
df.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,num_trades,taker_buy_base,taker_buy_quote,ignore,bid_volume,ask_volume,total_volume
0,2025-07-26 08:00:00,186.41,187.99,186.41,187.96,549552.94,2025-07-26 08:59:59.999,1.029060e+08,66919,321549.30,6.022148e+07,0,321549.30,228003.64,549552.94
1,2025-07-26 09:00:00,187.97,189.16,187.42,188.94,933487.36,2025-07-26 09:59:59.999,1.758321e+08,92016,502027.40,9.457083e+07,0,502027.40,431459.96,933487.36
2,2025-07-26 10:00:00,188.94,189.75,188.09,188.22,954186.81,2025-07-26 10:59:59.999,1.803950e+08,99528,423808.89,8.014049e+07,0,423808.89,530377.92,954186.81
3,2025-07-26 11:00:00,188.21,188.50,187.24,187.69,858101.65,2025-07-26 11:59:59.999,1.611837e+08,83855,354699.75,6.663413e+07,0,354699.75,503401.90,858101.65
4,2025-07-26 12:00:00,187.69,188.44,187.21,187.84,502553.74,2025-07-26 12:59:59.999,9.444184e+07,57501,270657.04,5.087016e+07,0,270657.04,231896.70,502553.74

In [11]:
df['Date'] = pd.to_datetime(df['open_time'])
df.dtypes

df.set_index('Date', inplace=True)
df.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,num_trades,taker_buy_base,taker_buy_quote,ignore,bid_volume,ask_volume,total_volume
Date,,,,,,,,,,,,,,,
2025-07-26 08:00:00,2025-07-26 08:00:00,186.41,187.99,186.41,187.96,549552.94,2025-07-26 08:59:59.999,1.029060e+08,66919,321549.30,6.022148e+07,0,321549.30,228003.64,549552.94
2025-07-26 09:00:00,2025-07-26 09:00:00,187.97,189.16,187.42,188.94,933487.36,2025-07-26 09:59:59.999,1.758321e+08,92016,502027.40,9.457083e+07,0,502027.40,431459.96,933487.36
2025-07-26 10:00:00,2025-07-26 10:00:00,188.94,189.75,188.09,188.22,954186.81,2025-07-26 10:59:59.999,1.803950e+08,99528,423808.89,8.014049e+07,0,423808.89,530377.92,954186.81
2025-07-26 11:00:00,2025-07-26 11:00:00,188.21,188.50,187.24,187.69,858101.65,2025-07-26 11:59:59.999,1.611837e+08,83855,354699.75,6.663413e+07,0,354699.75,503401.90,858101.65
2025-07-26 12:00:00,2025-07-26 12:00:00,187.69,188.44,187.21,187.84,502553.74,2025-07-26 12:59:59.999,9.444184e+07,57501,270657.04,5.087016e+07,0,270657.04,231896.70,502553.74

In [13]:
env = gym.make('stocks-v0', df=df, frame_bound=(5,10), window_size=5)
env.signal_features

NameNotFound: Environment stocks doesn't exist.